name: Docker Swarm Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/node-api-check:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-api-check:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH for Docker Swarm manager
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Docker Swarm
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SWARM_USER }}@${{ secrets.SWARM_MANAGER_IP }} << 'EOF'
            docker service update --force --image ${{ secrets.DOCKER_HUB_USERNAME }}/node-api-check:latest node-api-check-stack_app || \
            docker stack deploy -c /home/app-node/docker-swarm.yml node-api-check-stack
          EOF
